dofile("utilfunctions.lua")
dofile("tableExtensions.lua")
dofile("solutionItems.lua")
dofile("customProps.lua")
dofile("customTargets.lua")
dofile("exportables.lua")
dofile("kinds/lib.lua")
dofile("kinds/test.lua")
